# Generated by Django 3.2.6 on 2022-07-03 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billed_By',
            fields=[
                ('Billed_By_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('Business_Name', models.CharField(default='None', max_length=50)),
                ('Address', models.CharField(default='None', max_length=150, null=True)),
                ('Email', models.CharField(default='None', max_length=50)),
                ('Phone', models.CharField(default='None', max_length=50)),
                ('Business_GSTIN', models.IntegerField(null=True)),
                ('Business_PAN_Number', models.CharField(default='None', max_length=50, null=True)),
                ('VAT_Registration_Number', models.CharField(default='None', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Billed_To',
            fields=[
                ('Billed_To_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('Business_Name', models.CharField(default='None', max_length=50)),
                ('Address', models.CharField(default='None', max_length=150, null=True)),
                ('Email', models.CharField(default='None', max_length=50)),
                ('Phone', models.CharField(default='None', max_length=50)),
                ('Business_GSTIN', models.IntegerField(null=True)),
                ('Business_PAN_Number', models.CharField(default='None', max_length=50, null=True)),
                ('VAT_Registration_Number', models.CharField(default='None', max_length=50, null=True)),
                ('Unique_Key', models.CharField(default='None', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('client_company', models.CharField(default='None', max_length=50)),
                ('client_address', models.CharField(default='None', max_length=150, null=True)),
                ('client_phone', models.CharField(default='None', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_title', models.CharField(max_length=1000)),
                ('invoice_subtitle', models.CharField(max_length=1000)),
                ('Invoice_Date', models.CharField(default='None', max_length=50)),
                ('Due_Date', models.CharField(default='None', max_length=50)),
                ('Invoice_tax', models.CharField(default='None', max_length=50)),
                ('Invoice_currency', models.CharField(default='None', max_length=50)),
                ('Invoice_amount', models.FloatField()),
                ('Invoice_status', models.IntegerField(default=0, null=True)),
                ('Invoice_Billed_By', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trial.billed_by')),
                ('Invoice_Billed_To', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trial.billed_to')),
            ],
        ),
        migrations.CreateModel(
            name='User_OTP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_ver_OTP', models.CharField(blank=True, max_length=6, null=True)),
                ('ver_OTP_time', models.DateTimeField(auto_now=True, null=True)),
                ('pass_change_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('pass_OTP_time', models.DateTimeField(auto_now=True, null=True)),
                ('email_verified', models.BooleanField(blank=True, null=True)),
                ('auth_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_username', models.CharField(max_length=100, unique=True)),
                ('user_email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user_company', models.CharField(default='None', max_length=50, null=True)),
                ('user_address', models.CharField(default='None', max_length=150, null=True)),
                ('user_phone', models.CharField(default='None', max_length=50)),
                ('auth_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_title', models.CharField(max_length=50, null=True)),
                ('item_GST_Rate', models.CharField(max_length=50, null=True)),
                ('Quantity', models.IntegerField(null=True)),
                ('Rate', models.IntegerField(null=True)),
                ('Amount', models.IntegerField(null=True)),
                ('CGST', models.IntegerField(null=True)),
                ('SGST', models.IntegerField(null=True)),
                ('Total', models.IntegerField(null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trial.user')),
            ],
        ),
        migrations.CreateModel(
            name='invoice_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.IntegerField(null=True)),
                ('invoice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trial.invoice')),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trial.items')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='Invoiceitems',
            field=models.ManyToManyField(to='trial.items'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trial.client'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trial.user'),
        ),
        migrations.AddField(
            model_name='client',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trial.user'),
        ),
        migrations.AddField(
            model_name='billed_to',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trial.user'),
        ),
        migrations.AddField(
            model_name='billed_by',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trial.user'),
        ),
    ]
