# Generated by Django 3.2.6 on 2022-07-06 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0002_remove_invoice_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='Invoiceitems',
        ),
        migrations.AddField(
            model_name='invoice',
            name='Invoiceitems',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trial.items'),
        ),
    ]
