# Generated by Django 3.2.6 on 2022-07-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0004_auto_20220706_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Amount_inwords',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
