# Generated by Django 3.2.6 on 2022-07-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0005_invoice_amount_inwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Invoice_Total',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='Invoice_disc',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='Invoice_ship',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='Invoice_subtot',
            field=models.FloatField(default=0, null=True),
        ),
    ]
