# Generated by Django 3.2.6 on 2022-07-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0006_auto_20220718_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='Invoice_amount',
        ),
    ]
