# Generated by Django 3.2.6 on 2022-07-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0007_remove_invoice_invoice_amount'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='items',
            name='CGST',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='SGST',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='Total',
            field=models.FloatField(null=True),
        ),
    ]
